services:
  - type: web
    name: telegram-clicker-bot
    env: node
    buildCommand: npm install
    startCommand: npm run production
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: PORT
        value: 10000
